### ISSUE TITLE
Running twice causes chocolate to hang/crash

### ISSUE THREAD

**Issue by derekr** [drudge/github-flavored-markdown.chocmixin#1]
With the following code:

```
# Test

    ## Test

        Some code!
```

If I hit alt-cmd-P twice (or run from the menu twice) two windows open up with the resulting preview, but Chocolat beach balls after that.

May want to reuse the same window for previews.

**Comment by drudge** [comment]
I can't replicate this with 1.2-node4. Can you try that build?

**Comment by derekr** [comment]
Works a ok now.

Think it should target the same window when rendering?

**Comment by drudge** [comment]
The reason i didn't do it is because you might want to preview multiple docs at the same time. I guess i could store a hash bashed on filename and repurpose windows that way though.
